### ISSUE TITLE
Jakob isn't doing his part

### ISSUE THREAD

**Issue by za419** [za419/Jakobs-life#10]
Seriously, wtf is this?

**Comment by JakobFrank** [comment]
WOW is right! I am definitely glad this was brought to my attention.

**Comment by za419** [comment]
You're welcome

**Comment by JakobFrank** [comment]
Issue resolved

**Comment by za419** [comment]
Issue not resolved

**Comment by JakobFrank** [comment]
Repo owner has reverted my part's existence thus rending this issue redundant. Closing issue
