### ISSUE TITLE
Jakob is Jakob

### ISSUE THREAD

**Issue by za419** [za419/Jakobs-life#14]

**Comment by JakobFrank** [comment]
Jakob is actually only sometimes Jakob. Issue resolved

**Comment by za419** [comment]
Jakob should never be Jakob. Being Jakob is bad.

**Comment by JakobFrank** [comment]
The proof is in the pudding. Issue resolved

**Comment by za419** [comment]
There is no pudding.

**Comment by JakobFrank** [comment]
Repo owner has reverted pudding's existence thus rending this issue redundant. Closing issue
